import os

bt = chr(96)
lines = [
    '/**',
    ' * verify-runtime-key-chain.mjs',
    ' * Run: node scripts/verify-runtime-key-chain.mjs',
    ' * Output: runtime-key-verify-report.json',
    ' */',
    "import fs from 'node:fs';",
    "import path from 'node:path';",
    "import { fileURLToPath } from 'node:url';",
    '',
    'const __dirname = path.dirname(fileURLToPath(import.meta.url));',
    'const REPO_ROOT = path.resolve(__dirname, "..");',
    'const OUTPUT = path.join(REPO_ROOT, "runtime-key-verify-report.json");',
    'const R2 = "https://pub-e3dfe5c479f44fbc906aae6c475603db.r2.dev";',
    '',
    'function buildKey(id) { return ' + bt + 'question:${id}' + bt + '; }',
    '',
    'function resolveUrl(key, profileId) {',
    r'  const m = key.match(/^question:(\d+)$/i);',
    '  if (!m) return null;',
    '  const id = Number(m[1]);',
    '  if (!Number.isFinite(id) || id <= 0 || (profileId !== "vi-v1" && profileId !== "en-v1")) return null;',
    '  const p = ' + bt + 'audio/tts/assets/${profileId}/question/${id}.mp3' + bt + ';',
    '  const url = ' + bt + '${R2}/${p}' + bt + ';',
    '  const bad = ["texttospeech.googleapis.com","drive.usercontent.google.com","drive.google.com"];',
    '  for (const b of bad) if (url.includes(b)) return { error: ' + bt + 'FORBIDDEN:${b}' + bt + ', url };',
    '  return { path: p, url, id, profileId };',
    '}',
    '',
    'const auditJson = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, "question-id-uniqueness-audit.json"), "utf8"));',
    'const catPath = path.join(REPO_ROOT, "backend", "data", "tts", "catalog.json");',
    'const samples = [];',
    '',
    'if (fs.existsSync(catPath)) {',
    '  const cat = JSON.parse(fs.readFileSync(catPath, "utf8"));',
    '  const qs = (Array.isArray(cat.entries) ? cat.entries : []).filter(e => e.key && e.key.startsWith("question:") && e.profileId === "vi-v1");',
    '  const n = qs.length;',
    '  for (const pos of [0, Math.floor(n * .1), Math.floor(n * .25), Math.floor(n * .5), Math.floor(n * .7), Math.floor(n * .85), n - 1]) {',
    '    const e = qs[pos]; if (!e) continue;',
    r'    const mm = e.key.match(/^question:(\d+)$/);',
    '    if (mm) samples.push({ label: ' + bt + 'vi-v1-pos${pos}' + bt + ', questionId: Number(mm[1]), profileId: "vi-v1" });',
    '  }',
    '}',
    'samples.push({ label: "en-v1-q1901", questionId: 1901, profileId: "en-v1" });',
    'samples.push({ label: "en-v1-q1930", questionId: 1930, profileId: "en-v1" });',
    'if (samples.length === 0) for (const q of [1, 4000, 8000]) samples.push({ label: "fallback", questionId: q, profileId: "vi-v1" });',
    '',
    'console.log(' + bt + '[verify] Testing ${samples.length} samples...' + bt + ');',
    'const results = [];',
    'for (const s of samples) {',
    '  const key = buildKey(s.questionId);',
    '  const res = resolveUrl(key, s.profileId);',
    '  const keyOk = key === ' + bt + 'question:${s.questionId}' + bt + ' ? "PASS" : "FAIL";',
    '  if (!res || res.error) { results.push({ ...s, key, keyOk, urlErr: res && res.error || "NULL", pass: false }); continue; }',
    '  const expPath = ' + bt + 'audio/tts/assets/${s.profileId}/question/${s.questionId}.mp3' + bt + ';',
    '  const pathOk = res.path === expPath ? "PASS" : "FAIL:got=" + res.path;',
    '  const noGoogle = !res.url.includes("googleapis.com") && !res.url.includes("drive.usercontent");',
    '  let status = null, ct = null, noHtml = null, httpOk = null;',
    '  try {',
    '    const resp = await fetch(res.url, { method: "HEAD" });',
    '    status = resp.status;',
    '    ct = resp.headers.get("content-type") || "";',
    '    noHtml = !ct.includes("text/html");',
    '    httpOk = (status === 200 && noHtml && (ct.includes("audio") || ct.includes("octet-stream"))) ? "PASS" : "FAIL";',
    '  } catch (e) { httpOk = "ERROR:" + e.message; }',
    '  const pass = keyOk === "PASS" && pathOk === "PASS" && noGoogle && httpOk === "PASS";',
    '  results.push({ label: s.label, questionId: s.questionId, profileId: s.profileId, key, keyOk, path: res.path, url: res.url, pathOk, noGoogle, status, ct, noHtml, httpOk, pass });',
    '  console.log(' + bt + '  ${s.label} q=${s.questionId} => ${res.url} [${status}] ${pass ? "OK" : "FAIL"}' + bt + ');',
    '}',
    '',
    'const totalPass = results.filter(r => r.pass).length;',
    'const totalFail = results.filter(r => !r.pass).length;',
    'const verdict = totalFail === 0 && totalPass > 0 ? "PASS" : "FAIL";',
    'const report = { generatedAt: new Date().toISOString(), auditSource: auditJson.source, auditVerdict: auditJson.verdict, totalTested: results.length, totalPass, totalFail, overallVerdict: verdict, results };',
    'fs.writeFileSync(OUTPUT, JSON.stringify(report, null, 2) + "\\n", "utf8");',
    'console.log(' + bt + '[verify] VERDICT: ${verdict} (${totalPass}/${results.length})' + bt + ');',
    'console.log(' + bt + '[verify] Written to ${OUTPUT}' + bt + ');',
]
content = '\n'.join(lines) + '\n'

out_path = os.path.join(os.path.dirname(__file__), 'verify-runtime-key-chain.mjs')
with open(out_path, 'w', encoding='utf-8') as f:
    f.write(content)
print('OK wrote', len(content), 'chars to', out_path)
