import fs from 'fs';
import path from 'path';
import { seedLessons, seedQuestions } from '../src/data/seedData';

const finalDir = path.join(process.cwd(), 'content-patches', 'final');
const outFile = path.join(process.cwd(), 'src', 'data', 'generatedQuestionPatches.ts');

type PatchQuestion = {
  questionType: 'single_choice' | 'true_false' | 'fill_number' | 'ordering' | 'matching' | 'fill_text' | 'multi_choice';
  questionText: string;
  options: string[] | null;
  correctAnswer: string;
  explanationSimple: string;
  difficulty: 'easy' | 'medium' | 'hard';
  skillTag: string;
  isVerified?: 0 | 1;
};

type PatchLesson = {
  lessonId: number;
  grade: number;
  subjectCode: string;
  lessonTitle?: string;
  patches: PatchQuestion[];
};

type PatchFile = {
  subjectCode?: string;
  grade?: number;
  lessons?: PatchLesson[];
};

function walkJsonFiles(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walkJsonFiles(full));
    else if (entry.isFile() && entry.name.toLowerCase().endsWith('.json')) out.push(full);
  }
  return out;
}

function esc(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

const lessonMap = new Map(seedLessons.map((l) => [l.id, l]));
const maxExistingId = seedQuestions.reduce((max, q) => Math.max(max, q.id), 0);

const files = walkJsonFiles(finalDir);
if (files.length === 0) {
  console.log(`No patch files found in ${finalDir}`);
  process.exit(0);
}

let nextId = maxExistingId + 1;
const generatedRows: string[] = [];
let imported = 0;
let skipped = 0;

for (const file of files) {
  const raw = fs.readFileSync(file, 'utf8');
  let parsed: PatchFile;
  try {
    parsed = JSON.parse(raw) as PatchFile;
  } catch {
    console.warn(`Skip invalid JSON: ${file}`);
    skipped += 1;
    continue;
  }

  const lessons = parsed.lessons || [];
  for (const entry of lessons) {
    const lesson = lessonMap.get(entry.lessonId);
    if (!lesson) {
      console.warn(`Skip unknown lessonId ${entry.lessonId} in ${file}`);
      skipped += 1;
      continue;
    }

    for (const patch of entry.patches || []) {
      if (!patch.questionText || patch.questionText.includes('TODO:')) {
        skipped += 1;
        continue;
      }
      if (!patch.correctAnswer || patch.correctAnswer.includes('TODO')) {
        skipped += 1;
        continue;
      }

      const optionsJson = patch.options && patch.options.length > 0
        ? JSON.stringify(patch.options)
        : null;

      generatedRows.push(`  { id: ${nextId}, grade: ${lesson.grade}, subjectCode: '${esc(lesson.subjectCode)}', lessonId: ${lesson.id}, questionType: '${patch.questionType}', questionText: '${esc(patch.questionText)}', optionsJson: ${optionsJson ? `'${esc(optionsJson)}'` : 'null'}, correctAnswer: '${esc(patch.correctAnswer)}', explanationSimple: '${esc(patch.explanationSimple || '')}', difficulty: '${patch.difficulty}', skillTag: '${esc(patch.skillTag || `${lesson.subjectCode}_core`)}', sourceType: 'generated', isVerified: ${patch.isVerified ?? 0}, isActive: 1 },`);
      nextId += 1;
      imported += 1;
    }
  }
}

const fileText = [
  "import type { Question } from './seedData';",
  '',
  '/**',
  ' * Auto-generated by scripts/apply-question-patches.ts',
  ' * Do not edit by hand.',
  ' */',
  'export const generatedQuestionPatches: Question[] = [',
  ...generatedRows,
  '];',
  '',
].join('\n');

fs.writeFileSync(outFile, fileText, 'utf8');

console.log(`Patch files scanned: ${files.length}`);
console.log(`Imported questions: ${imported}`);
console.log(`Skipped entries: ${skipped}`);
console.log(`Output file: ${outFile}`);
